### ISSUE TITLE
Is the language expected to be compilable to a StructureMap?

### ISSUE THREAD

**Issue by axelv** [beda-software/FHIRPathMappingLanguage#10]
Hi, 
I think this is project is getting super interesting. 
But unfortunately I haven't got the time to dive in the code yet.

Just out of curiousity: do you expect the language to be compilable to a StructureMap?

Thanks

**Comment by ruscoder** [comment]
Hi @axelv! This project is an alternative way of doing mapping, so, it was not a goal to be compilable to a StructureMap.
