### ISSUE TITLE
Alternative to JUTE $if derective proposal

### ISSUE THREAD

**Issue by ruscoder** [beda-software/FHIRPathMappingLanguage#2]
It's not relevant for primitive types (str, number), because it might be expressed using FHIRpath `iif()`.
For complex structures, I can suggest something like switch:

```json
{
    "resourceType": "Bundle",
    "type": "transaction",
    "entry": [{
        "request": {
            "url": "/Observation",
            "method": "POST"
        },
        "resource": {
            "code": {
                "{{ QuestionnaireResponse.repeat(item).where(linkId='my-id').exists() }}": {
                     "display": "Branch then"
                 },
                // ...another branches might be here...
                "{{ QuestionnaireResponse.repeat(item).where(linkId='my-id').exists().not() }}": {
                     "display": "Branch else"
                 }
            }
        }
    }]
}
```

For implementation, it means if an object contains expression-keys and all of them are evaluated to boolean (array of one boolean element), then it should be handled as the switch.

It differs from #1, because all expressions must return booleans. Of course, there's an edge case, when #1 should map array of booleans, but it's not the case of usage.

**Comment by ir4y** [comment]
```json
{
    "resourceType": "Bundle",
    "type": "transaction",
    "entry": [{
        "request": {
            "url": "/Observation",
            "method": "POST"
        },
        "resource": {
            "code": {
                "{% if QuestionnaireResponse.repeat(item).where(linkId='my-id') = '1' %}": {
                     "display": "Branch then"
                 },
                "{% elsif QuestionnaireResponse.repeat(item).where(linkId='my-id').exists() = '2' %}": {
                     "display": "Branch two"
                 },
                "{% else %}": {
                    "display": "Branch else"
                }
            }
        }
    }]
}
```

**Comment by ir4y** [comment]
```json
{
    "resourceType": "Bundle",
    "type": "transaction",
    "entry": [{
        "request": {
            "url": "/Observation",
            "method": "POST"
        },
        "resource": {
            "code": {
                "{% case QuestionnaireResponse.repeat(item).where(linkId='my-id') %}": {
                    "{% when '2' %}": { // '1' is a FHIRPath expression
                         "display": "Branch then"
                     },
                    "{% when '2' %}": { // '2' is a FHIRPath expression
                         "display": "Branch two"
                     },
                    "{% else %}": {
                        "display": "Branch else"
                    }
                }
            }
        }
    }]
}
```

**Comment by ir4y** [comment]
Check if it is possible to use an extension to implement if and/or case logic (Check #4 for more details).

**Comment by ruscoder** [comment]
I added support for if and else, the examples are available in tests https://github.com/beda-software/FHIRPathMappingLanguage/blob/35441b4c0269423fab878121d061d5efc11fa8e5/ts/server/src/utils/extract.spec.ts#L402

If/else block should not contain user-defined keys because it's fully replaced with `if` or `else` branch blocks. 
In case `else` is missing for the false condition, the `null` will be returned.

The condition must be a single element with true or false, otherwise, an exception will be triggered. I think it's more obvious behavior than just returning `else` branch all the time. But it's not a final decision. So, let's think about it

**Comment by ruscoder** [comment]
I've decided to adhere to fhirpath's iif behavior by using implicitly `iif(expr, true, false)` under the hood.

https://github.com/beda-software/FHIRPathMappingLanguage/commit/4809e3d2bc8b33b7098a31070802b2793937319e

So, it works consistently with fhirpath conditions.
